# Model architecture and parameters
model_params: 
  type: baseline
  num_classes: 100

# Dataset configuration
dataset_params:
  dataset: DN4IL
  data_path: /fhome/amlai07/Adavanced_DP/Data/domainnet
  path_dn4il: /fhome/amlai07/Adavanced_DP/Data/DN4IL
  image_size: 384  
  batch_size: 24

# Training configuration
training_params:
  optimizer: Adam
  lr: 0.0001
  criterion: CrossEntropy
  epochs: 10

