# Teacher Student config only with EWC on student


# Dataset configuration
dataset_params:
  dataset: DN4IL
  data_path: /fhome/amlai07/Adavanced_DP/Data/domainnet
  path_dn4il: /fhome/amlai07/Adavanced_DP/Data/DN4IL
  image_size: 384  
  batch_size: 11

# Training configuration
training_params:
  mean_importances: False
  temperature: 5
  scheduler:
    name: StepLR
    step_size: 4
    gamma: 0.5
  criterion: CrossEntropy
  epochs: 10
  early_stopping_patience: -1
  optimizer: AdamW
  lr: 0.0001
  Approach: model_with_ewc

model_params: 
  type: baseline_with_ewc
  num_classes: 100
  train_with_ewc: True
  gradient_stop: False

ewc_params:
  lambda: 1
  
